### ISSUE TITLE
SCTP Restart Handling

### ISSUE THREAD

**Issue by teiclap** [gloinul/draft-westerlund-tsvwg-sctp-crypto-chunk#7]
SCTP Restart allows an SCTP Endpoint that has experienced a restart to resume an Association towards a remote Endpoint.
In case of Crypto Chunk that would need sending unencrypted INIT chunk, but such traffic will be discarded at the remote Endpoint thus there's no way to handle SCTP Restart.
On the other hand once an SCTP Endpoint has a restart, all the resources are lost including the Protection Engine and its state.
Last but not the least, permitting SCTP Restart would in some way open up to association hijacking.
The proposal is to explicitly state that SCTP Restart case is not supported.

**Comment by gloinul** [comment]
Fixed in PR #14
