### ISSUE TITLE
ASCONF support

### ISSUE THREAD

**Issue by teiclap** [gloinul/draft-westerlund-tsvwg-sctp-crypto-chunk#8]
ASCONF chunk transports information that are used for the identification of the Association, this allows the SCTP Endpoint to recognize the SCTP packet even if it comes from an unknown IP address.
SCTP Crypto chunk doesn't allow reading the ASCONF chunk before being decrypted, thus SCTP Endpoint has no criteria for accepting the SCTP packet based on ASCONF information.
It's suggested to fix that problem by describing the procedure to be used when as SCTP Endpoint supports ASCONF.
In case ASCONF is supported, the SCTP Endpoint will use the VTAG for giving a first criteria of acceptability, if the VTAG is known the Crypto Chunk will be sent to the Protection Engine for processing.

**Comment by gloinul** [comment]
Resolved in PR #13
